### ISSUE TITLE
Error in handling mouse.

### ISSUE THREAD

**Issue by Abhinav1217** [teamxenox/caligator#18]
Hi, Saw your post on dev.to, I thought I should try it out. I need converters a lot and google is sometimes just so slow. I am a linux user, so thanks for appimage, I appreciate it very much, 

I however have issue mouse input, I discovered when I was trying to switch theme. Mouse click isn't registered on dropdown menu, It just activate window dragging. I can switch theme via keyboard though.
And when I go back from settings, since editor is now out of focus, I can not click to get cursor back on editor. Worse that here, keyboard tabs doesn't always gain focus here (maybe I am counting tabs wrong cause I did get focus once, but never again.

I have a screen recording if I am unclear in explaining.

**Comment by SarathSantoshDamaraju** [comment]
Hi @Abhinav1217 
I will look into it. Please share the recording

**Comment by Abhinav1217** [comment]
[caligator-error.zip](https://github.com/sarthology/caligator/files/3670222/caligator-error.zip)

There is no sound, But at the end, before closing the caligator, when mouse click didn't give focus to the editor, I was trying to gain focus via tabs, Didn't work here. The theme switching was done by keyboard, not mouse scroll.

**Comment by grumpkin** [comment]
I noticed this on Windows as well. After clicking the settings button, it show's the Theme dropdown (which doesn't work) but after clicking the X to close settings you can no longer use the application as you can't get focus back into the entry box

**Comment by mauritzn** [comment]
Having the same issue here as well. I'm running Kubuntu 19.04 _(KDE)_, happens both with the AppImage and the deb file.

**Comment by sarthology** [comment]
@SarathSantoshDamaraju Is this issue closed ?

**Comment by SarathSantoshDamaraju** [comment]
@sarthology Yes. New build should fix it. Was unable to build an installable file last time. Will try building it this weekend

**Comment by Abhinav1217** [comment]
I just tried by building latest git head on master branch. This issue seems fixed. The release has not been tagged since September which is really old and buggy.  

The master branch resolves a lot of issues with Operational precedence and is also faster in loading. This is finally turning out to be nice utility.  Looking forward for new release.

**Comment by sarthology** [comment]
@SarathSantoshDamaraju @Abhinav1217 We are also firing this project up guys. Get upto dated at https://gitter.im/Caligatorapp/community#
