### ISSUE TITLE
Cold not load the dark theme

### ISSUE THREAD

**Issue by Mathanagopal97** [teamxenox/caligator#24]
I am not able to load the dark theme in your app. And it seems that the app is crashing after I try to select the theme. I have attached a zip (Steps.zip) that contains the .mht file which can be opened using Internet explorer. Please look into the issue. 
[Steps.zip](https://github.com/sarthology/caligator/files/3672341/Steps.zip)

**Comment by davask** [comment]
Hi,

I can t change the theme and I can t use the caligator after trying to change the theme.
I added a video of my attemtp to test it in the zip.
I m under WIndows8.1 using caligator-setup-0.0.1-0.exe
[caligator.zip](https://github.com/sarthology/caligator/files/3674820/caligator.zip)

**Comment by Tronerta** [comment]
Hi
Nothing happens when I click on theme selection dropdown on Linux Mint 19.3

**Comment by martinetmayank** [comment]
The app is in pre-release state. For now, what you can do is

1. Clone the repository

2. `cd caligator-master` 

3. `npm install && npm start` 

We will be updating the packages soon.
