### ISSUE TITLE
Close Hamburger Menu doesn't allow further input

### ISSUE THREAD

**Issue by themarkwilliams** [teamxenox/caligator#25]
If you click the More Hamburger Menu, you can change the theme fine, but then clicking the X takes you back to the main Caligator screen, but no input is recognized after going to the Hamburger menu. 

version 0.0.1 - Windows 10 x64

**Comment by martinetmayank** [comment]
There is something new which I experienced. If I start the Caligator by `npm start` it works fine rather than typing/searching on menu.

**Comment by martinetmayank** [comment]
The app is in pre-release state. For now, what you can do is

1. Clone the repository

2. `cd caligator-master`

3. `npm install && npm start`

We will be updating the packages soon.
