### ISSUE TITLE
Accessing hamburger menu makes the entire app unresponsive 

### ISSUE THREAD

**Issue by chintu0019** [teamxenox/caligator#29]
OS: **Archlabs**
DE: **i3**
Installation: using **appimage**

Issue description: The app gets stuck (unresponsive) after accessing the hamburger menu, consequently, cannot change the theme.
Also, after returning back from the menu, the editor is unresponsive and I cannot enter any value. Have to restart the app to use it.

**Comment by pavanjadhaw** [comment]
Hey thanks for creating issue,
I tried reproducing the issue but I wasnt able to on debian 10 along with dwm

**Comment by chintu0019** [comment]
Hi,

Is there a way to collect any logs?
Let me know if you need any other information from me that can help you
tackle this issue.

Regards,
Manoj

**Comment by cristiancristeatsg** [comment]
It happens on the Windows build. When compiling it works fine.

**Comment by martinetmayank** [comment]
The app is in pre-release state. For now, what you can do is

1. Clone the repository

2. `cd caligator-master`

3. `npm install && npm start`

We will be updating the packages soon.
