### ISSUE TITLE
The app gets stuck if I try to click on the menu to change the theme

### ISSUE THREAD

**Issue by ankushdas9** [teamxenox/caligator#42]
**Linux Distribution:** Pop!_OS 19.04
Installed using the .deb file.

With the default white theme - the app runs well without any issues.

However, when I try to change it to dark mode (which is kinda my priority) - the app gets stuck completely.

**Comment by bobthemac** [comment]
I am also having this issue but I am using Windows 10

**Comment by ChildishGiant** [comment]
https://gfycat.com/carefreeartisticgalapagosdove
![CarefreeArtisticGalapagosdove](https://thumbs.gfycat.com/CarefreeArtisticGalapagosdove-size_restricted.gif)

The cursor disappears and the theme dropdown does nothing

**Comment by martinetmayank** [comment]
The app is in pre-release state. For now, what you can do is

1. Clone the repository

2. `cd caligator-master`

3. `npm install && npm start`

We will be updating the packages soon.
