### ISSUE TITLE
Expressions in parentheses are not calculated before outside expressions

### ISSUE THREAD

**Issue by StephenCavender** [teamxenox/caligator#62]
Expressions within parentheses should be calculated before expressions outside.
<img width="328" alt="Screen Shot 2020-03-24 at 9 38 48 AM" src="https://user-images.githubusercontent.com/6619472/77431591-47d5f800-6db3-11ea-8319-885e2112ce41.png">

**Comment by StephenCavender** [comment]
Seems this issue has been fixed but is not in a release/pre-release.

**Comment by sarthology** [comment]
Yup !!
