### ISSUE TITLE
Resizing window goes wrong! 😯 (Click on the title to watch)

### ISSUE THREAD

**Issue by amaljoy258** [teamxenox/caligator#65]
👉 We need to set a **minimum window height and width.**

**When resizing horizontally:**
![Bug_2_H](https://user-images.githubusercontent.com/61835763/78140219-49548f80-7447-11ea-83ed-b187d085f8d8.gif)

**When resizing vertically:**
![Bug_2_V](https://user-images.githubusercontent.com/61835763/78140347-7dc84b80-7447-11ea-90fb-9e0d6babbdae.gif)

**Comment by huonggiangbui** [comment]
Interested! Can I take this issue?

**Comment by amaljoy258** [comment]
**Solved this issue.** ✔

![bug-fix-resize](https://user-images.githubusercontent.com/61835763/78421406-eba58a80-7674-11ea-8b4e-703599e3db59.gif)
