### ISSUE TITLE
Can't change theme app stops working after trying to change theme.

### ISSUE THREAD

**Issue by wildcard-f8** [teamxenox/caligator#75]
I installed the deb package on Ubuntu 20.04 and the app works fine until I try to change the theme. First I can't change the theme. I try to exit out of the theme selector but the app doesn't accept anymore inputs.

[Screencast from Friday, 14 August, 2020 01:28:25 AM PST.zip](https://github.com/teamxenox/caligator/files/5070502/Screencast.from.Friday.14.August.2020.01.28.25.AM.PST.zip)

Love the app. Hope it gets fixed.

**Comment by martinetmayank** [comment]
Actually, the `deb` package is not yet updated.

**Comment by wildcard-f8** [comment]
I guess I got too excited.

**Comment by martinetmayank** [comment]
The app is in pre-release state. For now, what you can do is

1. Clone the repository

2. cd caligator-master

3. `npm install && npm start`

We will be updating the packages soon.
