### ISSUE TITLE
can't change to dark mode in windows 10?

### ISSUE THREAD

**Issue by spaciousmind** [teamxenox/caligator#76]
hi there, just downloaded this... I wanted something similar to numi on mac and this looks very nice but it just freezes when I goto options and try to change from light mode?

**Comment by martinetmayank** [comment]
The app is in pre-release state. For now, what you can do is

1. Clone the repository

2. cd caligator-master

3. `npm install && npm start`

We will be updating the packages soon.

**Comment by spaciousmind** [comment]
ok great thanks
